# API 文件自動產生

name: Generate API Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Redoc CLI
        run: npm install -g redoc-cli
      - name: Generate API HTML
        run: redoc-cli bundle docs/API_LIBRARY.yaml -o docs/API.html
      - name: Upload API Docs
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs/API.html
